//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Slats.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Slats.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slats.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentGrid.
        /// </summary>
        public static string ContentGridPageTitle {
            get {
                return ResourceManager.GetString("ContentGridPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataGrid.
        /// </summary>
        public static string DataGridPageTitle {
            get {
                return ResourceManager.GetString("DataGridPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Authentication.
        /// </summary>
        public static string DialogAuthenticationTitle {
            get {
                return ResourceManager.GetString("DialogAuthenticationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no internet connection, please connect to the internet and try again..
        /// </summary>
        public static string DialogNoNetworkAvailableContent {
            get {
                return ResourceManager.GetString("DialogNoNetworkAvailableContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong during the login, please try again..
        /// </summary>
        public static string DialogStatusUnknownErrorContent {
            get {
                return ResourceManager.GetString("DialogStatusUnknownErrorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DropFiles {
            get {
                object obj = ResourceManager.GetObject("DropFiles", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Orders.
        /// </summary>
        public static string MasterDetailListDescription {
            get {
                return ResourceManager.GetString("MasterDetailListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MasterDetail.
        /// </summary>
        public static string MasterDetailPageTitle {
            get {
                return ResourceManager.GetString("MasterDetailPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Medical {
            get {
                object obj = ResourceManager.GetObject("Medical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Minion {
            get {
                object obj = ResourceManager.GetObject("Minion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Psychiatry {
            get {
                object obj = ResourceManager.GetObject("Psychiatry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Psychology_Trans {
            get {
                object obj = ResourceManager.GetObject("Psychology_Trans", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings page placeholder text.  Your app description goes here..
        /// </summary>
        public static string SettingsPageAboutText {
            get {
                return ResourceManager.GetString("SettingsPageAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this application.
        /// </summary>
        public static string SettingsPageAboutTitle {
            get {
                return ResourceManager.GetString("SettingsPageAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Theme.
        /// </summary>
        public static string SettingsPageChooseThemeText {
            get {
                return ResourceManager.GetString("SettingsPageChooseThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string SettingsPageLogInButtonText {
            get {
                return ResourceManager.GetString("SettingsPageLogInButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string SettingsPageLogOutButtonText {
            get {
                return ResourceManager.GetString("SettingsPageLogOutButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no user logged in, please click &quot;Log In&quot; to log in..
        /// </summary>
        public static string SettingsPageNoUserLoggedInText {
            get {
                return ResourceManager.GetString("SettingsPageNoUserLoggedInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalization.
        /// </summary>
        public static string SettingsPagePersonalizationTitle {
            get {
                return ResourceManager.GetString("SettingsPagePersonalizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Statement.
        /// </summary>
        public static string SettingsPagePrivacyStatementText {
            get {
                return ResourceManager.GetString("SettingsPagePrivacyStatementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string SettingsPageRadioButtonDarkTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string SettingsPageRadioButtonLightTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string SettingsPageRadioButtonWindowsDefaultTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonWindowsDefaultTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string SettingsPageUserTitle {
            get {
                return ResourceManager.GetString("SettingsPageUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinical Reviews.
        /// </summary>
        public static string ShellGroupAdminCPRHeader {
            get {
                return ResourceManager.GetString("ShellGroupAdminCPRHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataGrid.
        /// </summary>
        public static string ShellMenuItemViewsDataGridPageHeader {
            get {
                return ResourceManager.GetString("ShellMenuItemViewsDataGridPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paperwork.
        /// </summary>
        public static string ShellMenuItemViewsFileManagerPageHeader {
            get {
                return ResourceManager.GetString("ShellMenuItemViewsFileManagerPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MasterDetail.
        /// </summary>
        public static string ShellMenuItemViewsMasterDetailPageHeader {
            get {
                return ResourceManager.GetString("ShellMenuItemViewsMasterDetailPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Poll Calendar.
        /// </summary>
        public static string ShellMenuLeavePollHeader {
            get {
                return ResourceManager.GetString("ShellMenuLeavePollHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrgChart.
        /// </summary>
        public static string ShellMenuViewsOrgChartCommand {
            get {
                return ResourceManager.GetString("ShellMenuViewsOrgChartCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPR Assignment Maker.
        /// </summary>
        public static string ShellPageHeaderCprAssignmentMakerVM {
            get {
                return ResourceManager.GetString("ShellPageHeaderCprAssignmentMakerVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPR Review (admin).
        /// </summary>
        public static string ShellPageHeaderCprAssignmentReviewAdminVM {
            get {
                return ResourceManager.GetString("ShellPageHeaderCprAssignmentReviewAdminVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPR Review (staff).
        /// </summary>
        public static string ShellPageHeaderCprAssignmentReviewStaffVM {
            get {
                return ResourceManager.GetString("ShellPageHeaderCprAssignmentReviewStaffVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPR Review (supervisor).
        /// </summary>
        public static string ShellPageHeaderCprAssignmentReviewSupervisorVM {
            get {
                return ResourceManager.GetString("ShellPageHeaderCprAssignmentReviewSupervisorVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPR Summary.
        /// </summary>
        public static string ShellPageHeaderCprAssignmentSummaryVM {
            get {
                return ResourceManager.GetString("ShellPageHeaderCprAssignmentSummaryVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPR Builder.
        /// </summary>
        public static string ShellPageHeaderCprBuilderVM {
            get {
                return ResourceManager.GetString("ShellPageHeaderCprBuilderVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Manager.
        /// </summary>
        public static string ShellPageHeaderDataManagerVM {
            get {
                return ResourceManager.GetString("ShellPageHeaderDataManagerVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Fill.
        /// </summary>
        public static string ShellPageHeaderFormFillVM {
            get {
                return ResourceManager.GetString("ShellPageHeaderFormFillVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Manager.
        /// </summary>
        public static string ShellPageHeaderFormManagerVM {
            get {
                return ResourceManager.GetString("ShellPageHeaderFormManagerVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Poll Calendar.
        /// </summary>
        public static string ShellPageHeaderLeavePollVM {
            get {
                return ResourceManager.GetString("ShellPageHeaderLeavePollVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Attendance (admin).
        /// </summary>
        public static string ShellPageHeaderMeetingAttendAdminVM {
            get {
                return ResourceManager.GetString("ShellPageHeaderMeetingAttendAdminVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Attendance.
        /// </summary>
        public static string ShellPageHeaderMeetingAttendanceVM {
            get {
                return ResourceManager.GetString("ShellPageHeaderMeetingAttendanceVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Attendance (staff).
        /// </summary>
        public static string ShellPageHeaderMeetingAttendStaffVM {
            get {
                return ResourceManager.GetString("ShellPageHeaderMeetingAttendStaffVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Attendance (supervisor).
        /// </summary>
        public static string ShellPageHeaderMeetingAttendSupervisorVM {
            get {
                return ResourceManager.GetString("ShellPageHeaderMeetingAttendSupervisorVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Info.
        /// </summary>
        public static string ShellPageHeaderProgramInfoVM {
            get {
                return ResourceManager.GetString("ShellPageHeaderProgramInfoVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Designer.
        /// </summary>
        public static string ShellPageHeaderReportDesignerVM {
            get {
                return ResourceManager.GetString("ShellPageHeaderReportDesignerVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Page.
        /// </summary>
        public static string ShellPageHeaderReportPageVM {
            get {
                return ResourceManager.GetString("ShellPageHeaderReportPageVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Viewer.
        /// </summary>
        public static string ShellPageHeaderReportViewerVM {
            get {
                return ResourceManager.GetString("ShellPageHeaderReportViewerVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Day.
        /// </summary>
        public static string ShellPageHeaderScheduleDayVM {
            get {
                return ResourceManager.GetString("ShellPageHeaderScheduleDayVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule PP.
        /// </summary>
        public static string ShellPageHeaderSchedulePpVM {
            get {
                return ResourceManager.GetString("ShellPageHeaderSchedulePpVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Staff.
        /// </summary>
        public static string ShellPageHeaderScheduleStaffVM {
            get {
                return ResourceManager.GetString("ShellPageHeaderScheduleStaffVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Week.
        /// </summary>
        public static string ShellPageHeaderScheduleWeekVM {
            get {
                return ResourceManager.GetString("ShellPageHeaderScheduleWeekVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Detail.
        /// </summary>
        public static string ShellPageHeaderStaffDetailVM {
            get {
                return ResourceManager.GetString("ShellPageHeaderStaffDetailVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Lisst (admin).
        /// </summary>
        public static string ShellPageHeaderStaffListAdminVM {
            get {
                return ResourceManager.GetString("ShellPageHeaderStaffListAdminVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff List (staff).
        /// </summary>
        public static string ShellPageHeaderStaffListStaffVM {
            get {
                return ResourceManager.GetString("ShellPageHeaderStaffListStaffVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff List (supervisor).
        /// </summary>
        public static string ShellPageHeaderStaffListSupervisorVM {
            get {
                return ResourceManager.GetString("ShellPageHeaderStaffListSupervisorVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staffy Group 1.
        /// </summary>
        public static string ShellPageRibbonAdminGroupCommon1Header {
            get {
                return ResourceManager.GetString("ShellPageRibbonAdminGroupCommon1Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staffy Group 2.
        /// </summary>
        public static string ShellPageRibbonAdminGroupCommon2Header {
            get {
                return ResourceManager.GetString("ShellPageRibbonAdminGroupCommon2Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ShellPageRibbonBackstageTabSettingsHeader {
            get {
                return ResourceManager.GetString("ShellPageRibbonBackstageTabSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentialing.
        /// </summary>
        public static string ShellPageRibbonHomeGroupCredentialingHeader {
            get {
                return ResourceManager.GetString("ShellPageRibbonHomeGroupCredentialingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string ShellPageRibbonHomeGroupGeneralHeader {
            get {
                return ResourceManager.GetString("ShellPageRibbonHomeGroupGeneralHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Group 1.
        /// </summary>
        public static string ShellPageRibbonManagementGroupCommon1Header {
            get {
                return ResourceManager.GetString("ShellPageRibbonManagementGroupCommon1Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Group 2.
        /// </summary>
        public static string ShellPageRibbonManagementGroupCommon2Header {
            get {
                return ResourceManager.GetString("ShellPageRibbonManagementGroupCommon2Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staffy Group 1.
        /// </summary>
        public static string ShellPageRibbonProgramGroupCommon1Header {
            get {
                return ResourceManager.GetString("ShellPageRibbonProgramGroupCommon1Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staffy Group 2.
        /// </summary>
        public static string ShellPageRibbonProgramGroupCommon2Header {
            get {
                return ResourceManager.GetString("ShellPageRibbonProgramGroupCommon2Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Group 1.
        /// </summary>
        public static string ShellPageRibbonSupervisorGroupCommon1Header {
            get {
                return ResourceManager.GetString("ShellPageRibbonSupervisorGroupCommon1Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Group 2.
        /// </summary>
        public static string ShellPageRibbonSupervisorGroupCommon2Header {
            get {
                return ResourceManager.GetString("ShellPageRibbonSupervisorGroupCommon2Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string ShellPageRibbonTabAdminHeader {
            get {
                return ResourceManager.GetString("ShellPageRibbonTabAdminHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string ShellPageRibbonTabHomeHeader {
            get {
                return ResourceManager.GetString("ShellPageRibbonTabHomeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string ShellPageRibbonTabManagementHeader {
            get {
                return ResourceManager.GetString("ShellPageRibbonTabManagementHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs.
        /// </summary>
        public static string ShellPageRibbonTabProgramHeader {
            get {
                return ResourceManager.GetString("ShellPageRibbonTabProgramHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor.
        /// </summary>
        public static string ShellPageRibbonTabSupervisorHeader {
            get {
                return ResourceManager.GetString("ShellPageRibbonTabSupervisorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string ShellPageRibbonTabToolsHeader {
            get {
                return ResourceManager.GetString("ShellPageRibbonTabToolsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Chart.
        /// </summary>
        public static string ShellPageRibbonToolsGroupCommon1Header {
            get {
                return ResourceManager.GetString("ShellPageRibbonToolsGroupCommon1Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow Charts.
        /// </summary>
        public static string ShellPageRibbonToolsGroupCommon2Header {
            get {
                return ResourceManager.GetString("ShellPageRibbonToolsGroupCommon2Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back (Alt + Left).
        /// </summary>
        public static string WebViewPageBackButtonTooltip {
            get {
                return ResourceManager.GetString("WebViewPageBackButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page failed to load. Check connection and retry..
        /// </summary>
        public static string WebViewPageFaildedMessage {
            get {
                return ResourceManager.GetString("WebViewPageFaildedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward (Alt + Right).
        /// </summary>
        public static string WebViewPageForwardButtonTooltip {
            get {
                return ResourceManager.GetString("WebViewPageForwardButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string WebViewPageLoadingText {
            get {
                return ResourceManager.GetString("WebViewPageLoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in browser (Ctrl + T).
        /// </summary>
        public static string WebViewPageOpenInBrowserButtonTooltip {
            get {
                return ResourceManager.GetString("WebViewPageOpenInBrowserButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh (F5).
        /// </summary>
        public static string WebViewPageRefreshButtonTooltip {
            get {
                return ResourceManager.GetString("WebViewPageRefreshButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Work_in_Progress {
            get {
                object obj = ResourceManager.GetObject("Work_in_Progress", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
