//public ICommand MenuViewsOrgChartCommand => _menuOrgChartCommand ?? (_menuOrgChartCommand = new RelayCommand(OnMenuOrgChartDetail));
//public ICommand MenuViewsMasterDetailCommand => _menuViewsMasterDetailCommand ?? (_menuViewsMasterDetailCommand = new RelayCommand(OnMenuViewsMasterDetail));
//public ICommand CprAssignmentMakerCommand => _menuCprAssignmentMakerCommand ?? (_menuCprAssignmentMakerCommand = new RelayCommand(OnCprAssignmentMaker));
//public ICommand CprReviewAdminCommand => _menuCprReviewAdminCommand ?? (_menuCprReviewAdminCommand = new RelayCommand(OnCprReviewAdmin));
//public ICommand CprReviewStaffCommand => _menuCprReviewStaffCommand ?? (_menuCprReviewStaffCommand = new RelayCommand(OnCprReviewStaff));
//public ICommand CprReviewSupervisorCommand => _menuCprReviewSupervisorCommand ?? (_menuCprReviewSupervisorCommand = new RelayCommand(OnCprReviewSupervisor));
//public ICommand CprSummaryCommand => _menuCprSummaryCommand ?? (_menuCprSummaryCommand = new RelayCommand(OnCprSummary));
//public ICommand CprBuilderCommand => _menuCprBuilderCommand ?? (_menuCprBuilderCommand = new RelayCommand(OnCprBuilder));
//public ICommand DataManagerCommand => _menuDataManagerCommand ?? (_menuDataManagerCommand = new RelayCommand(OnDataManager));
//public ICommand FormFillCommand => _menuFormFillCommand ?? (_menuFormFillCommand = new RelayCommand(OnFormFill));
//public ICommand FormManagerCommand => _menuFormManagerCommand ?? (_menuFormManagerCommand = new RelayCommand(OnFormManager));
//public ICommand MeetingAttendAdminCommand => _menuMeetingAttendAdminCommand ?? (_menuMeetingAttendAdminCommand = new RelayCommand(OnMeetingAttendAdmin));
//public ICommand MeetingAttendanceCommand => _menuMeetingAttendanceCommand ?? (_menuMeetingAttendanceCommand = new RelayCommand(OnMeetingAttendance));
//public ICommand MeetingAttendStaffCommand => _menuMeetingAttendStaffCommand ?? (_menuMeetingAttendStaffCommand = new RelayCommand(OnMeetingAttendStaff));
//public ICommand MeetingAttendSupervisorCommand => _menuMeetingAttendSupervisorCommand ?? (_menuMeetingAttendSupervisorCommand = new elayCommandOnMeetingAttendSupervisor));
//public ICommand ReportDesignerCommand => _menuReportDesignerCommand ?? (_menuReportDesignerCommand = new RelayCommand(OnReportDesigner));
//public ICommand ReportPageCommand => _menuReportPageCommand ?? (_menuReportPageCommand = new RelayCommand(OnReportPage));
//public ICommand ReportViewerCommand => _menuReportViewerCommand ?? (_menuReportViewerCommand = new RelayCommand(OnReportViewer));
//public ICommand ScheduleDayCommand => _menuScheduleDayCommand ?? (_menuScheduleDayCommand = new RelayCommand(OnScheduleDay));
//public ICommand SchedulePpCommand => _menuSchedulePpCommand ?? (_menuSchedulePpCommand = new RelayCommand(OnSchedulePp));
//public ICommand ScheduleStaffCommand => _menuScheduleStaffCommand ?? (_menuScheduleStaffCommand = new RelayCommand(OnScheduleStaff));
//public ICommand ScheduleWeekCommand => _menuScheduleWeekCommand ?? (_menuScheduleWeekCommand = new RelayCommand(OnScheduleWeek));
//public ICommand StaffDetailCommand => _menuStaffDetailCommand ?? (_menuStaffDetailCommand = new RelayCommand(OnStaffDetail));
//public ICommand StaffListAdminCommand => _menuStaffListAdminCommand ?? (_menuStaffListAdminCommand = new RelayCommand(OnStaffListAdmin));
//public ICommand StaffListStaffCommand => _menuStaffListStaffCommand ?? (_menuStaffListStaffCommand = new RelayCommand(OnStaffListStaff));
//public ICommand StaffListSupervisorCommand => _menuStaffListSupervisorCommand ?? (_menuStaffListSupervisorCommand = new RelayCommand(OnStaffListSupervisor));
//public ICommand ProgramInfoCommand => _menuProgramInfoCommand ?? (_menuProgramInfoCommand = new RelayCommand(OnProgramInfo));
//public ICommand LeavePollCommand => _menuLeavePollCommand ?? (_menuLeavePollCommand = new RelayCommand(OnLeavePoll));
//public ICommand MenuViewsFileManagerCommand => _menuViewsFileManagerCommand ?? (_menuViewsFileManagerCommand = new RelayCommand(OnFileManager));
//public ICommand MenuNewEditPersonCommand => _menuNewEditPersonCommand ?? (_menuNewEditPersonCommand = new RelayCommand(OnNewEditPerson));
//public ICommand MenuViewsDataGridCommand => _menuViewsDataGridCommand ?? (_menuViewsDataGridCommand = new RelayCommand(OnMenuViewsDataGrid));

//private void OnNewEditPerson() => _navigationService.NavigateTo(typeof(NewEditPersonVM).FullName, null, true);
//private void OnMenuOrgChartDetail() => _navigationService.NavigateTo(typeof(OrgChartVM).FullName, null, true);
//private void OnMenuViewsMasterDetail() => _navigationService.NavigateTo(typeof(MasterDetailViewModel).FullName, null, true);
//private void OnMenuViewsDataGrid() => _navigationService.NavigateTo(typeof(DataGridViewModel).FullName, null, true);
//private void OnCprAssignmentMaker() => _navigationService.NavigateTo(typeof(CprAssignmentMakerVM).FullName, null, true);
//private void OnCprReviewAdmin() => _navigationService.NavigateTo(typeof(CprReviewAdminVM).FullName, null, true);
//private void OnCprReviewStaff() => _navigationService.NavigateTo(typeof(CprReviewStaffVM).FullName, null, true);
//private void OnCprReviewSupervisor() => _navigationService.NavigateTo(typeof(CprReviewSupervisorVM).FullName, null, true);
//private void OnCprSummary() => _navigationService.NavigateTo(typeof(CprSummaryVM).FullName, null, true);
//private void OnCprBuilder() => _navigationService.NavigateTo(typeof(CprBuilderVM).FullName, null, true);
//private void OnDataManager() => _navigationService.NavigateTo(typeof(DataManagerVM).FullName, null, true);
//private void OnFormFill() => _navigationService.NavigateTo(typeof(FormFillVM).FullName, null, true);
//private void OnFormManager() => _navigationService.NavigateTo(typeof(FormManagerVM).FullName, null, true);
//private void OnMeetingAttendAdmin() => _navigationService.NavigateTo(typeof(MeetingAttendAdminVM).FullName, null, true);
//private void OnMeetingAttendance() => _navigationService.NavigateTo(typeof(MeetingAttendanceVM).FullName, null, true);
//private void OnMeetingAttendStaff() => _navigationService.NavigateTo(typeof(MeetingAttendStaffVM).FullName, null, true);
//private void OnMeetingAttendSupervisor() => _navigationService.NavigateTo(typeof(MeetingAttendSupervisorVM).FullName, null, true);
//private void OnReportDesigner() => _navigationService.NavigateTo(typeof(ReportDesignerVM).FullName, null, true);
//private void OnReportPage() => _navigationService.NavigateTo(typeof(ReportPageVM).FullName, null, true);
//private void OnReportViewer() => _navigationService.NavigateTo(typeof(ReportViewerVM).FullName, null, true);
//private void OnScheduleDay() => _navigationService.NavigateTo(typeof(ScheduleDayVM).FullName, null, true);
//private void OnSchedulePp() => _navigationService.NavigateTo(typeof(SchedulePpVM).FullName, null, true);
//private void OnScheduleStaff() => _navigationService.NavigateTo(typeof(ScheduleStaffVM).FullName, null, true);
//private void OnScheduleWeek() => _navigationService.NavigateTo(typeof(ScheduleWeekVM).FullName, null, true);
//private void OnStaffDetail() => _navigationService.NavigateTo(typeof(StaffDetailVM).FullName, null, true);
//private void OnStaffListAdmin() => _navigationService.NavigateTo(typeof(StaffListAdminVM).FullName, null, true);
//private void OnStaffListStaff() => _navigationService.NavigateTo(typeof(StaffListStaffVM).FullName, null, true);
//private void OnStaffListSupervisor() => _navigationService.NavigateTo(typeof(StaffListSupervisorVM).FullName, null, true);
//private void OnProgramInfo() => _navigationService.NavigateTo(typeof(ProgramInfoVM).FullName, null, true);
//private void OnLeavePoll() => _navigationService.NavigateTo(typeof(LeavePollVM).FullName, null, true);
//private void OnFileManager() => _navigationService.NavigateTo(typeof(FileManagerVM).FullName, null, true);